### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by vonmoosa** [arcpy/update-hosted-feature-service#25]
Am I limited to 1000 features for each feature service when running the update this way? Or will I be able to update a feature service with over 70,000 features?

**Comment by dokebi** [comment]
I am getting an error at the Stage Service geoprocessing tool.

>>> Starting Feature Service publish process
found Feature Service : b32e2b8980cf41e58b83be7f63bf2074
found Service Definition : c784bbce87c440c985a427f8e00c5e39
Traceback (most recent call last):
  File "C:\Python27\ArcGISx6410.5\Lib\site-packages\pythonwin\pywin\framework\scriptutils.py", line 325, in RunScript
    exec codeObject in __main__.__dict__
  File "F:\HOW TO\PYTHON\Projects\RSA\Publishing Services to AGOL\github\Update_Hosted_Feature_Service\update.py", line 521, in <module>
    makeSD(MXD, serviceName, tempDir, finalSD, maxRecords, tags, summary)
  File "F:\HOW TO\PYTHON\Projects\RSA\Publishing Services to AGOL\github\Update_Hosted_Feature_Service\update.py", line 454, in makeSD
    arcpy.StageService_server(newSDdraft, outputSD)
  File "C:\Program Files (x86)\ArcGIS\Desktop10.5\ArcPy\arcpy\server.py", line 1401, in StageService
    raise e
ExecuteError: ERROR 001269: Compressing the service definition failed.
Failed to execute (StageService).

I was informed a bug (BUG-000096416) on this geoprocessing tool.  Has it been resolved?
Is it not possible to automate the publishing due to the bug?
