### ISSUE TITLE
Bug in StageService geoprocessing tool?

### ISSUE THREAD

**Issue by dokebi** [arcpy/update-hosted-feature-service#26]
I am getting an error at the Stage Service geoprocessing tool.

            Starting Feature Service publish process
            found Feature Service : b32e2b8980cf41e58b83be7f63bf2074
            found Service Definition : c784bbce87c440c985a427f8e00c5e39
            Traceback (most recent call last):
            File "C:\Python27\ArcGISx6410.5\Lib\site-packages\pythonwin\pywin\framework\scriptutils.py", line 325, in RunScript
            exec codeObject in main.dict
            File "F:\HOW TO\PYTHON\Projects\RSA\Publishing Services to AGOL\github\Update_Hosted_Feature_Service\update.py", line 521, in
            makeSD(MXD, serviceName, tempDir, finalSD, maxRecords, tags, summary)
            File "F:\HOW TO\PYTHON\Projects\RSA\Publishing Services to AGOL\github\Update_Hosted_Feature_Service\update.py", line 454, in makeSD
            arcpy.StageService_server(newSDdraft, outputSD)
            File "C:\Program Files (x86)\ArcGIS\Desktop10.5\ArcPy\arcpy\server.py", line 1401, in StageService
            raise e
            ExecuteError: ERROR 001269: Compressing the service definition failed.
            Failed to execute (StageService).

Also, I was informed a bug (BUG-000096416) on this geoprocessing tool. Has it been resolved?
Is it not possible to automate the publishing due to the bug?

**Comment by CortD** [comment]
The bug occurs only when calling the 64 bit version of Python.  The error message you posted shows you are using the 64 bit version (File "C:\Python27\ArcGIS**x64**10.5).   Try explicitly calling the 32 bit version of Python.
