### ISSUE TITLE
Script will not update feature service

### ISSUE THREAD

**Issue by lagiboo** [arcpy/update-hosted-feature-service#29]
I have the mxd and script all in one folder, I have updated the Settings.ini and when I run the python script I get the following?  I am not a programmer so I am having trouble figuring out what is going on here:

>>> Starting Feature Service publish process
Traceback (most recent call last):
  File "C:\Python27\ArcGIS10.2\Lib\site-packages\Pythonwin\pywin\framework\scriptutils.py", line 321, in RunScript
    debugger.run(codeObject, __main__.__dict__, start_stepping=1)
  File "C:\Python27\ArcGIS10.2\Lib\site-packages\Pythonwin\pywin\debugger\__init__.py", line 60, in run
    _GetCurrentDebugger().run(cmd, globals,locals, start_stepping)
  File "C:\Python27\ArcGIS10.2\Lib\site-packages\Pythonwin\pywin\debugger\debugger.py", line 655, in run
    exec cmd in globals, locals
  File "L:\ED\GIS CAD Systems\GIS_Projects\Outage\Python Script Test\UpdateOutagePoints_Server.py", line 5, in <module>
    import ConfigParser
  File "L:\ED\GIS CAD Systems\GIS_Projects\Outage\Python Script Test\UpdateOutagePoints_Server.py", line 37, in __init__
    self.token = self.getToken(username, password)
  File "L:\ED\GIS CAD Systems\GIS_Projects\Outage\Python Script Test\UpdateOutagePoints_Server.py", line 55, in getToken
    token_response = self.url_request(token_url, query_dict, 'POST')
  File "L:\ED\GIS CAD Systems\GIS_Projects\Outage\Python Script Test\UpdateOutagePoints_Server.py", line 304, in url_request
    response = urllib2.urlopen(req)
  File "C:\Python27\ArcGIS10.2\lib\urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "C:\Python27\ArcGIS10.2\lib\urllib2.py", line 404, in open
    response = self._open(req, data)
  File "C:\Python27\ArcGIS10.2\lib\urllib2.py", line 422, in _open
    '_open', req)
  File "C:\Python27\ArcGIS10.2\lib\urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "C:\Python27\ArcGIS10.2\lib\urllib2.py", line 1222, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "C:\Python27\ArcGIS10.2\lib\urllib2.py", line 1184, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 10054] An existing connection was forcibly closed by the remote host>

Any help would be appreciated.

Thanks,

Laura

**Comment by lagiboo** [comment]
Here is what I get when I run it via CMD:

Starting Feature Service publish process
Traceback (most recent call last):
  File "L:\ED\GIS CAD Systems\GIS_Projects\Outage\Python Script Test\UpdateOutagePoints_Server.py", line 519, in <module>
    agol = AGOLHandler(inputUsername, inputPswd, serviceName, folderName, False)
  File "L:\ED\GIS CAD Systems\GIS_Projects\Outage\Python Script Test\UpdateOutagePoints_Server.py", line 37, in __init__
    self.token = self.getToken(username, password)
  File "L:\ED\GIS CAD Systems\GIS_Projects\Outage\Python Script Test\UpdateOutagePoints_Server.py", line 55, in getToken
    token_response = self.url_request(token_url, query_dict, 'POST')
  File "L:\ED\GIS CAD Systems\GIS_Projects\Outage\Python Script Test\UpdateOutagePoints_Server.py", line 304, in url_request
    response = urllib2.urlopen(req)
  File "C:\Python27\ArcGIS10.2\lib\urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "C:\Python27\ArcGIS10.2\lib\urllib2.py", line 404, in open
    response = self._open(req, data)
  File "C:\Python27\ArcGIS10.2\lib\urllib2.py", line 422, in _open
    '_open', req)
  File "C:\Python27\ArcGIS10.2\lib\urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "C:\Python27\ArcGIS10.2\lib\urllib2.py", line 1222, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "C:\Python27\ArcGIS10.2\lib\urllib2.py", line 1184, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 10054] An existing connection was forcibly closed by the remote host>
