### ISSUE TITLE
update.py fails to upload SD

### ISSUE THREAD

**Issue by tpcolson** [arcpy/update-hosted-feature-service#6]
For a MXD from which a service can be successfully overwritten when publishing from ArcMap, the same service cannot be updated using update.py with the following error:

Starting Feature Service publish process
found Feature Service : f4c43de7a4964371b1fbba68eaa15cfb
found Service Definition : d4333434f3c34a75b14b5d42fe811345
Created X:\GIS_Final\data\basedata\basemap\Data\Working\Python_Automated_Scripts\UPDATE_AGOL\tempDir\GRSM_TRAIL_INVENTORY.sd

Traceback (most recent call last):
  File "X:\GIS_Final\data\basedata\basemap\Data\Working\Python_Automated_Scripts\UPDATE_AGOL\update.py", line 309, in <module>
    if upload(finalSD, tags, description):
  File "X:\GIS_Final\data\basedata\basemap\Data\Working\Python_Automated_Scripts\UPDATE_AGOL\update.py", line 171, in upload
    response = requests.post(url, files=filesUp);
  File "C:\Python27\ArcGIS10.2\Lib\site-packages\requests\api.py", line 109, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Python27\ArcGIS10.2\Lib\site-packages\requests\api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "C:\Python27\ArcGIS10.2\Lib\site-packages\requests\sessions.py", line 451, in request
    prep = self.prepare_request(req)
  File "C:\Python27\ArcGIS10.2\Lib\site-packages\requests\sessions.py", line 382, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Python27\ArcGIS10.2\Lib\site-packages\requests\models.py", line 296, in prepare
    self.prepare_body(data, files, json)
  File "C:\Python27\ArcGIS10.2\Lib\site-packages\requests\models.py", line 444, in prepare_body
    (body, content_type) = self._encode_files(files, data)
  File "C:\Python27\ArcGIS10.2\Lib\site-packages\requests\models.py", line 150, in _encode_files
    fdata = fp.read()
MemoryError

**Comment by arcpy** [comment]
This should be fixed with PR #7
